// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://sytpnohpeftforwycfzb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dHBub2hwZWZ0Zm9yd3ljZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNjk1MDgsImV4cCI6MjA0ODk0NTUwOH0.U8aLU2uhuNLh8JaLM6ZE4apPikdjlSJ-gbNDIT4IzfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);